language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

script:
  # Update composer to latest version.
  - composer self-update || true
  # Validate composer.json file.
  - composer validate
  # Try to install all requirements.
  - composer install
  # Try to convert markdown to html
  - composer check-markdown

notifications:
  email: false